name: "Parent Issue updater"
description: "Create epics from GitHub Issues using parent-child links"
author: "Taras Kushnir"
inputs:
  TOKEN:
    description: "Github token"
    default: ""
  REPO:
    description: "Github repository"
    default: ""
  DRY_RUN:
    description: "Do not update real issues"
    default: ""
  SYNC_DAYS:
    description: "Update issues changed in the last sync days"
    default: "1"
  ADD_CHANGELOG:
    description: "Add comments with updates made to parent issues"
    default: "1"
  MAX_LEVELS:
    description: "Show max levels of nested issues in parent"
    default: "0"
  UPDATE_CLOSED:
    description: "Update closed parent issues too"
    default: "0"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "link"
  color: "blue"

